---

- name: Checking if puppetlabs release package is installed
  apt:
    name: puppetlabs-release-pc1
    state: present
  ignore_errors: True
  register: puppet__release_package_installed
  when: ansible_os_family == "Debian"

- include: install.debian.yml
  when: (puppet__release_package_installed| failed) and (ansible_os_family == "Debian")
